version: '3'
services:
  neo4j:
    image: neo4j:4.4.5
    restart: unless-stopped
    ports:
      - "4111:7474"
      - "4112:7687"
    volumes:
      - ./conf:/root/neo4j/conf
      - ./data:/root/neo4j/data
      - ./import:/root/neo4j/import
      - ./logs:/root/neo4j/logs
      - ./plugins:/root/neo4j/plugins
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*,apoc.*
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_AUTH=neo4j/test
  app:
    build: .
    restart: unless-stopped
    ports:
      - "4115:4115"
    depends_on:
      - neo4j
